name: base
channels:
  # - conda-forge
  - defaults
dependencies:
  - numpy=1.23.4
  - pandas=1.5.2
  - pathlib=1.0.1
  - pathlib2=2.3.6
  - pip=22.2.2
  - python=3.10.8
  - streamlit=1.15.2
  - pip:
      # - biopython==1.76
      # - matplotlib==3.4.2
      - LiPydomics==1.6.8
